# Generates native/src/emoji.hpp from the Unicode emoji-test.txt data file.
# Includes every fully-qualified emoji except skin-tone variants. The emitted
# header is committed so the native build stays offline (mirrors gen-icons.ps1).
param(
  [string]$Source = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 3.0

$outPath = Join-Path $PSScriptRoot "..\native\src\emoji.hpp"
Write-Host "Downloading $Source ..."
$text = (Invoke-WebRequest -Uri $Source -UseBasicParsing -TimeoutSec 60).Content
$lines = $text -split "`r?`n"

# Build a literal for one entry: {L"<value escapes>", L"<label>", {L"kw", ...}}.
function Escape-Literal([string]$s) {
  return $s.Replace('\', '\\').Replace('"', '\"')
}

$group = ""
$subgroup = ""
$entries = New-Object System.Collections.Generic.List[string]
$seenValues = New-Object System.Collections.Generic.HashSet[string]

foreach ($line in $lines) {
  if ($line.StartsWith("# group:")) { $group = $line.Substring(8).Trim(); continue }
  if ($line.StartsWith("# subgroup:")) { $subgroup = $line.Substring(11).Trim(); continue }
  if ($line.Length -eq 0 -or $line.StartsWith("#")) { continue }

  $semi = $line.IndexOf(';')
  $hash = $line.IndexOf('#')
  if ($semi -lt 0 -or $hash -lt 0) { continue }

  $codes = $line.Substring(0, $semi).Trim()
  $status = $line.Substring($semi + 1, $hash - $semi - 1).Trim()
  if ($status -ne "fully-qualified") { continue }

  # Comment tail looks like:  <emoji> E<ver> <name>
  $tail = $line.Substring($hash + 1).Trim()
  $parts = $tail -split '\s+', 3
  if ($parts.Count -lt 3) { continue }
  $name = $parts[2].Trim()
  if ($name -match 'skin tone') { continue }

  # Build the \U escaped value from the space-separated hex codepoints.
  $value = ""
  foreach ($cp in ($codes -split '\s+')) {
    $value += "\U" + $cp.PadLeft(8, '0').ToUpper()
  }
  if (-not $seenValues.Add($value)) { continue }

  # Keywords: tokens from the name + subgroup, lowercased, deduped, length >= 2.
  $kwSource = ($name + " " + ($subgroup -replace '-', ' '))
  $tokens = ($kwSource.ToLower() -split '[^a-z0-9]+') | Where-Object { $_.Length -ge 2 } | Select-Object -Unique
  $kwLiteral = ($tokens | ForEach-Object { 'L"' + (Escape-Literal $_) + '"' }) -join ', '

  $label = Escape-Literal $name
  $entries.Add("    {L`"$value`", L`"$label`", {$kwLiteral}},")
}

Write-Host ("Parsed {0} emoji entries." -f $entries.Count)

$header = @"
#pragma once

// Generated by scripts/gen-emoji.ps1 from the Unicode emoji-test.txt data file.
// Do not edit by hand; re-run the script to regenerate.

#include "symbols.hpp"

#include <algorithm>
#include <string>
#include <vector>
#include <mutex>

namespace feathercast::emoji {

inline std::vector<feathercast::symbols::Symbol>* g_EmojiList = nullptr;
inline std::vector<feathercast::core::SearchItem>* g_EmojiSearchItems = nullptr;
inline std::mutex g_EmojiMutex;

inline const std::vector<feathercast::symbols::Symbol>& AllEmojiUnlocked();

inline const std::vector<feathercast::symbols::Symbol>& AllEmoji() {
  std::lock_guard<std::mutex> lock(g_EmojiMutex);
  return AllEmojiUnlocked();
}

inline void FreeEmojiMemory() {
  std::lock_guard<std::mutex> lock(g_EmojiMutex);
  if (g_EmojiList) {
    delete g_EmojiList;
    g_EmojiList = nullptr;
  }
  if (g_EmojiSearchItems) {
    delete g_EmojiSearchItems;
    g_EmojiSearchItems = nullptr;
  }
}

inline const std::vector<feathercast::symbols::Symbol>& AllEmojiUnlocked() {
  if (!g_EmojiList) {
    g_EmojiList = new std::vector<feathercast::symbols::Symbol>{
$($entries -join "`n")
  };
  }
  return *g_EmojiList;
}

inline std::vector<feathercast::symbols::Symbol> SearchEmoji(std::wstring query, size_t limit = 300) {
  query = feathercast::core::Trim(std::move(query));

  std::lock_guard<std::mutex> lock(g_EmojiMutex);
  const auto& all = AllEmojiUnlocked();
  std::vector<feathercast::symbols::Symbol> out;
  if (query.empty()) {
    for (const auto& emoji : all) {
      out.push_back(emoji);
      if (out.size() >= limit) break;
    }
    return out;
  }

  if (!g_EmojiSearchItems) {
    g_EmojiSearchItems = new std::vector<feathercast::core::SearchItem>();
    g_EmojiSearchItems->reserve(all.size());
    for (size_t i = 0; i < all.size(); ++i) {
      feathercast::core::SearchItem item;
      item.id = std::to_wstring(i);
      item.kind = L"emoji";
      item.source = L"emoji";
      item.name = all[i].label;
      item.keywords = all[i].keywords;
      g_EmojiSearchItems->push_back(std::move(item));
    }
  }

  const auto order = feathercast::core::Search(query, *g_EmojiSearchItems);
  for (const auto index : order) {
    out.push_back(all[index]);
    if (out.size() >= limit) break;
  }
  return out;
}

}  // namespace feathercast::emoji
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath (Split-Path $outPath)).Path + "\emoji.hpp", $header, $utf8NoBom)
Write-Host "Wrote $outPath"
